### ISSUE TITLE
Having the `good_model` and `starting_model` to be the same size might be impractical sometimes

### ISSUE THREAD

**Issue by jwhhh** [inlab-geo/espresso#102]
As the title, Hoel and I started a discussion about whether (or why) we insist that `good_model` and `starting_model` should be of the same size. 

I understand that the reason is obvious from a user's point of view (simplicity and shorter learning curve for conducting a new experiment on a new problem). 

Also from it can be impractical to ensure they have the same size due to the following reasons (from Hoel):
> When doing EM inversions, the mesh is generally discretized with cell sizes that are increasing with depth. This is because of the loss of resolution of the method at depth, also related to the exponential decay of the EM field with depth. It could be possible to discretize linearly as you did in the example you sent me, but it would result in too many cells, which would increase the time to run a forward simulation (and then the inversion).
>
> Also, it is a bit impractical when setting up a true model (like I did in example 2) to have to define a mesh that will be used as a true mesh for the starting mesh and for the inversion, then to construc the true model check what depths correspond to a specific cell number, and change manually each intervals to define the true model.

This also reminds me of [a case where the true model is defined with a different parameterisation](https://github.com/inlab-geo/cofi-examples/blob/main/examples/pygimli_ert/pygimli_ert.ipynb).

Could I get some advice and/or thoughts from @valentineap and @JuergHauser ? Thanks.

**Comment by valentineap** [comment]
The Espresso concept is to provide people with easy access to test problems, with a standardised interface so that it is easy to 'try out' a variety of problems without requiring significant domain knowledge. I think this requires a model space with a fixed dimension -- otherwise one needs to understand the internal details of the model space parameterisation in order to understand how to add or remove parameters. I therefore think we should keep things as they are for now -- we can always revisit this later if needed.

This may be inefficient or limiting, but I think that's OK -- Espresso exists to serve a very specific purpose. 

Note that contributors can define additional attributes beyond those required by the API, e.g. one could choose to have a `high_resolution_model` attribute to illustrate the 'ideal' solution, which is then projected into a lower-dimensional space to be 'good_model'.
