### ISSUE TITLE
Rewrite Espresso installation process; delay compilation until it's needed and not found

### ISSUE THREAD

**Issue by jwhhh** [inlab-geo/espresso#88]
On MacOS it's hard for the Fortran executable for find the correct libgfortran.

Following this, we can create a build status table automatically for all problems.

**Comment by valentineap** [comment]
@msambridge and I discussed this -- and the broader issue of how Espresso should manage compiled codes -- at some length. We propose to avoid trying to be too clever(!), and leave any non-Python installation to the end user. It does not seem realistic to try and support all possible platforms and scenarios -- and some examples could conceivably depend on forward codes that are licensed in a way that makes it problematic for us to bundle them within espresso.

There are (I think) two main cases to deal with.

1. The example depends on one or more standalone executables, i.e. the espresso functions simply use `subprocess.Popen` or similar to run an external program and read in their results. We should initially just assume that the necessary executable can be found on the path[^1] and try and run. If this fails, we report an error to the user along with a contributor-provided set of instructions on how to obtain and install the necessary code. At one end of the spectrum this might be 'Go to this website and follow the instructions'; at the other end of the spectrum it would be "go to <directory> and run `install.sh`".[^2] Either way it is up to the end-user to resolve any issues specific to their platform/setup, and up to the contributor to make the installation process as painless as possible.
2. The example relies on Cython/f2py interfaces. This is perhaps a bit trickier as the machinery is likely to be unfamiliar to end users, but I think we can follow a similar path. We can: (i) suggest that contributors consider making their own pip-installable package that provides the necessary functions as a standalone module, which espresso can then install and run; (ii) make some limited attempt to compile stuff if it is easy and everything works the first time; (iii) fail and let the contributor explain to the user what they should do to finish the installation process.

Obviously this approach will make the package a bit less plug-and-play for users, and will potentially introduce some difficulties for automatic verification of all examples. However I think it's probably better to focus on making it transparent for users to see what needs to be installed and where any errors arise, rather than trying to handle all possibilities ourselves and thus making it difficult for people to make sense of/troubleshoot errors when they do arise.


[^1]: Some thought is required about precisely which path we search. Just the system path? A custom `$ESPRESSOPATH` variable? Something more fine-grained e.g. `<espresso_dir>/<example_dir>/bin:$ESPRESSOPATH:$PATH`?
[^2]: We could consider having a mechanism for espresso to automagically attempt to run `install.sh` when a binary cannot be found.

**Comment by jwhhh** [comment]
I'd like to add some comments here for future reference.

Here are some options we've considered:
1. package and install all together (tried)
2. package all source code and compile when imported (current)
3. package the core and handle downloads of others (like [spacy](https://spacy.io/usage))
4. serve as a package manager (like conda-forge)

We started with option 1 initially, and at the point of closing this issue we switched to option 2. Some discussions were going on with conda-forge team when we were trying to upload espresso onto conda-forge (See https://github.com/conda-forge/staged-recipes/pull/21795), hence we need to make a decision to switch to either option 1 or 3.

Changing espresso back to option 1, with pip install extras and conditional import will be one thing we'll do first. Option 3 will probably be closer to how we want this project to end up.
